use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'qdmonekit_Example' do
  pod 'qdmonekit', :path => '../'

  target 'qdmonekit_Tests' do
    inherit! :search_paths

    
  end
end
